title: CTF Writeups
author: Nissen96
description: Writeups for various CTFs
google_analytics:
google_site_verification_content: 

#Usernames and badges
htb_badge_no:
thm_badge_no: 428409
show_thm_htb_badges_in_nav: true
github_username: Nissen96
gitlab:
medium:
stackoverflow_id: 6415512
hacker_news:
linkedin: 
twitch:
twitter: Nissen_96
reddit:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
